package interfaces;

import entities.Piloto;
import entities.Vuelo;
import org.hibernate.Session;
import org.hibernate.Transaction;

public class PantallaBorradoVuelo extends javax.swing.JFrame {

    private Session session;

    public PantallaBorradoVuelo(Session session) {
        initComponents();

        this.session = session;
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idVueloTextField = new javax.swing.JTextField();
        cancelarBorradoButton = new javax.swing.JButton();
        borrarVueloButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BORRADO DE UN VUELO");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("ID del vuelo:");

        idVueloTextField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        idVueloTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cancelarBorradoButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cancelarBorradoButton.setText("CANCELAR");
        cancelarBorradoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBorradoButtonActionPerformed(evt);
            }
        });

        borrarVueloButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        borrarVueloButton.setText("INSERTAR");
        borrarVueloButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarVueloButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cancelarBorradoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(borrarVueloButton)
                        .addGap(51, 51, 51))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27)
                        .addComponent(idVueloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(idVueloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrarVueloButton)
                    .addComponent(cancelarBorradoButton))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarBorradoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBorradoButtonActionPerformed
        this.dispose();
        PantallaPrincipal nuevaPantallaPrincipal = new PantallaPrincipal(session);
    }//GEN-LAST:event_cancelarBorradoButtonActionPerformed

    private void borrarVueloButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarVueloButtonActionPerformed

        StringBuilder posibleError = new StringBuilder("El vuelo con ID" + idVueloTextField.getText() + ", ha sido eliminado correctamente.\n");
        Transaction transaction = null;
        Vuelo vueloABorrar = new Vuelo();

        try {
            vueloABorrar = session.get(Vuelo.class, Integer.parseInt(idVueloTextField.getText()));
            System.out.println(vueloABorrar);

            if (vueloABorrar.equals(null)) {
                throw new Exception();

            } else {

                transaction = session.beginTransaction();
                session.remove(vueloABorrar);
                transaction.commit();

            }

        } catch (Exception e) {

            if (transaction != null) {
                transaction.rollback();
                posibleError = new StringBuilder();
                posibleError.append("La transacción no pudo iniciarse correctamente... Cancelando operación...\n"
                        + e.getMessage());

            } else {
                posibleError = new StringBuilder();
                posibleError.append("El avión con ID " + idVueloTextField.getText() + ", "
                        + "no se ha podido eliminar por un ERROR, cancelando operación...\n"
                        + e.getMessage());
            }
        }

        this.dispose();
        PantallaPrincipal newPantallaPrincipal = new PantallaPrincipal(session, posibleError);
        this.dispose();
    }//GEN-LAST:event_borrarVueloButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarVueloButton;
    private javax.swing.JButton cancelarBorradoButton;
    private javax.swing.JTextField idVueloTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
